
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Providers } from "./provider";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <div className="dark text-foreground bg-background">
        <Providers>
        <Header />
          <main >
            {children}
          </main>
          <Footer />
        </Providers>
        </div>
      </body>
    </html>
  );
}
